{
 "title": "Live Solare",
 "tags": [ "live" ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "price", "label": "€ / KWh", "query": "0.26" },
   {
    "name": "Oggi",
    "query": "select last(Heute_TS) from Statistik"
   },
   {
    "name": "Ieri",
    "query": "select last(Gestern_TS) from Statistik"
   },
   {
    "name": "QuestoMese",
    "query": "select last(DieserMonat_TS) from Statistik"
   }
  ]
 },
 "panels": [
  {
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "alias": "Datum",
     "measurement": "Info",
     "select": [
      [
       { "params": [ "Datum" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 5, "x": 6, "y": 0 },
   "options": {
    "content": "<center><font color=\"#C15C17\" size=6 >SolarEdge</font></center>"
   }
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 11, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "alias": "Datum",
     "measurement": "Info",
     "select": [
      [
       { "params": [ "Produkt" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 5, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "alias": ".",
     "measurement": "Service",
     "select": [
      [
       { "params": [ "Status" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    },
    {
     "alias": "Efficienza",
     "measurement": "AC",
     "query": "SELECT abs(\"Wirkungsgrad\") FROM \"AC\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "Wirkungsgrad" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " *-1" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Temperatura Inverter",
   "type": "stat",
   "gridPos": { "h": 2, "w": 5, "x": 19, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Temperatura Inverter",
     "measurement": "Service",
     "select": [
      [
       { "params": [ "Temperatur" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Produzione Solare",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "measurement": "data",
     "query": "SELECT last(\"value\") FROM \"data\" WHERE (\"device\" = 'SDM2301.1' AND \"type\" = 'Power') AND \"value\" >= 0 AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "device", "operator": "=", "value": "SDM1.1" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "PowerL1" }
     ]
    }
   ]
  },
  {
   "title": "Immissione - Prelievo",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "measurement": "data",
     "query": "SELECT last(\"value\") FROM \"data\" WHERE (\"device\" = 'SDM2301.2' AND \"type\" = 'Power') AND $timeFilter\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "device", "operator": "=", "value": "SDM1.2" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "PowerL1" }
     ]
    }
   ]
  },
  {
   "title": "Consumo",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expression": "A['sdm_cs'] + ( B['sdm_fv'] > 0 ? B['sdm_fv'] : 0)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "outputMetricName": "consumo",
     "periods": 7,
     "query": "SELECT mean(\"sdm_1\") + mean(\"sdm_2\") as \"consumomax\"  FROM\n( \nSELECT last(\"value\") as \"sdm_1\" FROM \"autogen\".\"data\" WHERE (\"device\" = 'SDM2301.1' AND \"type\" = 'Power') AND \"value\" >= 0 AND $timeFilter GROUP BY time($__interval) fill(previous)\n), \n(\nSELECT last(\"value\") as \"sdm_2\" FROM \"autogen\".\"data\" WHERE (\"device\" = 'SDM2301.2' AND \"type\" = 'Power') AND $timeFilter GROUP BY time($__interval) fill(previous)\n)\nGROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "timeshiftUnit": "days"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 8, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "alias": "Max Potenza Istantanea \"Produzione\"",
     "measurement": "data",
     "query": "SELECT mean(\"value\") FROM \"autogen\".\"data\" WHERE (\"device\" = 'SDM2301.1' AND \"type\" = 'Power') AND $timeFilter GROUP BY time($__interval) tz('Europe/Rome')",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "device", "operator": "=", "value": "SDM1.1" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "PowerL1" }
     ]
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 8, "x": 8, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "alias": "Max Potenza Istantanea \"Immissione\"",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"value\") * -1 FROM \"autogen\".\"data\" WHERE (\"device\" = 'SDM2301.2' AND \"type\" = 'Power') AND $timeFilter GROUP BY time($__interval) tz('Europe/Rome')",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 8, "x": 16, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "alias": "Max Potenza Istantanea \"Consumo\"",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"prelievo_immissione\") + mean(\"Produzione_Solare\") as \"consumo\"  FROM\n( \nSELECT mean(\"value\") as  \"prelievo_immissione\" FROM \"autogen\".\"data\" WHERE (\"device\" = 'SDM2301.2' AND \"type\" = 'Power') AND $timeFilter GROUP BY time($__interval) fill(previous)  tz('Europe/Rome')\n), \n(\nSELECT mean(\"value\") as \"Produzione_Solare\" FROM \"autogen\".\"data\" WHERE (\"device\" = 'SDM2301.1' AND \"type\" = 'Power')  AND $timeFilter  GROUP BY time($__interval) fill(previous) tz('Europe/Rome')\n)\nGROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "alias": "Produzione di oggi",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT difference(last(\"value\")) FROM \"data\" WHERE (\"device\" = 'SDM2301.1' AND \"type\" = 'Import') AND $timeFilter GROUP BY time(24h) fill(previous) tz('Europe/Rome')",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Autoconsumo di oggi",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"produzione\") - mean(\"immissione\") as \"autoconsumo\"  FROM\n( \nSELECT difference(last(\"value\")) as \"prelievo\" FROM \"autogen\".\"data\" WHERE (\"device\" = 'SDM2301.2' AND \"type\" = 'Import') AND $timeFilter GROUP BY time(1d) fill(null) tz('Europe/Rome')\n), \n(\nSELECT difference(last(\"value\")) as \"immissione\" FROM \"autogen\".\"data\" WHERE (\"device\" = 'SDM2301.2' AND \"type\" = 'Export') AND $timeFilter GROUP BY time(1d) fill(null) tz('Europe/Rome')\n),\n(\nSELECT difference(last(\"value\")) as \"produzione\" FROM \"autogen\".\"data\" WHERE (\"device\" = 'SDM2301.1' AND \"type\" = 'Import') AND \"value\" >= 0 AND $timeFilter GROUP BY time(1d) fill(null) tz('Europe/Rome')\n)\nGROUP BY time(1d) fill(null) tz('Europe/Rome')",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Immissione",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT difference(last(\"value\")) as \"immissione\" FROM \"autogen\".\"data\" WHERE (\"device\" = 'SDM2301.2' AND \"type\" = 'Export') AND $timeFilter GROUP BY time(1d) fill(null) tz('Europe/Rome')",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Consumo di oggi",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"prelievo\") + mean(\"produzione\") - mean(\"immissione\") as \"consumo\"  FROM\n( \nSELECT difference(last(\"value\")) as \"prelievo\" FROM \"autogen\".\"data\" WHERE (\"device\" = 'SDM2301.2' AND \"type\" = 'Import') AND $timeFilter GROUP BY time(1d) fill(null) tz('Europe/Rome')\n), \n(\nSELECT difference(last(\"value\")) as \"immissione\" FROM \"autogen\".\"data\" WHERE (\"device\" = 'SDM2301.2' AND \"type\" = 'Export') AND $timeFilter GROUP BY time(1d) fill(null) tz('Europe/Rome')\n),\n(\nSELECT difference(last(\"value\")) as \"produzione\" FROM \"autogen\".\"data\" WHERE (\"device\" = 'SDM2301.1' AND \"type\" = 'Import') AND \"value\" >= 0 AND $timeFilter GROUP BY time(1d) fill(null) tz('Europe/Rome')\n)\nGROUP BY time(1d) fill(null) tz('Europe/Rome')",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Prelievo di oggi",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT difference(last(\"value\")) FROM \"data\" WHERE (\"device\" = 'SDM2301.2' AND \"type\" = 'Import') AND $timeFilter GROUP BY time(24h) fill(previous) tz('Europe/Rome')",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "% di Consumo di Oggi",
   "type": "stat",
   "gridPos": { "h": 3, "w": 7, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expression": "$A / $C * 100", "type": "math" },
    { "expression": "$P / $C * 100", "type": "math" }
   ]
  },
  {
   "title": "% Consumo di Produzione",
   "type": "stat",
   "gridPos": { "h": 3, "w": 7, "x": 7, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expression": "$A / $C * 100", "type": "math" },
    { "expression": "$P / $C * 100", "type": "math" }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 10, "x": 14, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "alias": "Risparmio di oggi",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT (mean(\"produzione\") - mean(\"immissione\")) * [[price]] as \"autoconsumo\"  FROM\n( \nSELECT difference(last(\"value\")) as \"prelievo\" FROM \"autogen\".\"data\" WHERE (\"device\" = 'SDM2301.2' AND \"type\" = 'Import') AND $timeFilter GROUP BY time(1d) fill(null) tz('Europe/Rome')\n), \n(\nSELECT difference(last(\"value\")) as \"immissione\" FROM \"autogen\".\"data\" WHERE (\"device\" = 'SDM2301.2' AND \"type\" = 'Export') AND $timeFilter GROUP BY time(1d) fill(null) tz('Europe/Rome')\n),\n(\nSELECT difference(last(\"value\")) as \"produzione\" FROM \"autogen\".\"data\" WHERE (\"device\" = 'SDM2301.1' AND \"type\" = 'Import') AND $timeFilter GROUP BY time(1d) fill(null) tz('Europe/Rome')\n)\nGROUP BY time(1d) fill(null) tz('Europe/Rome')",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Spesa di oggi",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT (difference(last(\"value\"))) * [[price]] FROM \"data\" WHERE (\"device\" = 'SDM2301.2' AND \"type\" = 'Import') AND $timeFilter GROUP BY time(24h) fill(previous) tz('Europe/Rome')",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT integral(\"Leistung\",1h) from \"PV\" where time >= $Oggi",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "type": "gauge",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "measurement": "PV",
     "select": [
      [
       { "params": [ "Spannung" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "amper",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"Strom\" FROM \"PV\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Immissione & Autoconsumo",
   "type": "graph",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "watth", "label": "Potenza Media (W)" }
   ],
   "targets": [
    {
     "alias": "Immissione",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "data",
     "query": "SELECT mean(\"value\") * -1 FROM \"autogen\".\"data\" WHERE (\"device\" = 'SDM2301.2' AND \"type\" = 'Power') AND $timeFilter GROUP BY time($__interval) tz('Europe/Rome')",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "device", "operator": "=", "value": "SDM1.1" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "PowerL1" }
     ],
     "tz": "Europe/Rome"
    },
    {
     "alias": "Energia Solare",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "data",
     "query": "SELECT mean(\"value\") FROM \"autogen\".\"data\" WHERE (\"device\" = 'SDM2301.1' AND \"type\" = 'Power') AND $timeFilter GROUP BY time($__interval) tz('Europe/Rome')",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "device", "operator": "=", "value": "SDM1.2" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "PowerL1" }
     ],
     "tz": "Europe/Rome"
    },
    {
     "alias": "Consumo",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"prelievo_immissione\") + mean(\"Produzione_Solare\") as \"consumo\"  FROM\n( \nSELECT mean(\"value\") as  \"prelievo_immissione\" FROM \"autogen\".\"data\" WHERE (\"device\" = 'SDM2301.2' AND \"type\" = 'Power') AND $timeFilter GROUP BY time($__interval) fill(previous)  tz('Europe/Rome')\n), \n(\nSELECT mean(\"value\") as \"Produzione_Solare\" FROM \"autogen\".\"data\" WHERE (\"device\" = 'SDM2301.1' AND \"type\" = 'Power')  AND $timeFilter  GROUP BY time($__interval) fill(previous) tz('Europe/Rome')\n)\nGROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    { "target": "sun_altitude" }
   ]
  },
  {
   "title": "Produzione di Oggi",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "watth", "label": "Potenza Media (W)" }
   ],
   "targets": [
    { "target": "sun_altitude" },
    {
     "alias": "Produzione Inverter",
     "measurement": "AC",
     "query": "SELECT \"Leistung\" FROM \"AC\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "Leistung" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Produzione di Ieri",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 34 },
   "yaxes": [
    { "format": "watth", "label": "Potenza Media (W)" }
   ],
   "targets": [
    { "target": "sun_altitude" },
    {
     "alias": "Produzione Inverter",
     "measurement": "AC",
     "query": "SELECT \"Leistung\" FROM \"AC\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "Leistung" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "kwatt" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "alias": "Autoconsumo",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"produzione\") - mean(\"immissione\") as \"autoconsumo\"  FROM\n( \nSELECT difference(last(\"value\")) as \"prelievo\" FROM \"autogen\".\"data\" WHERE (\"device\" = 'SDM2301.2' AND \"type\" = 'Import') AND $timeFilter GROUP BY time(1d) fill(null) tz('Europe/Rome')\n), \n(\nSELECT difference(last(\"value\")) as \"immissione\" FROM \"autogen\".\"data\" WHERE (\"device\" = 'SDM2301.2' AND \"type\" = 'Export') AND $timeFilter GROUP BY time(1d) fill(null) tz('Europe/Rome')\n),\n(\nSELECT difference(last(\"value\")) as \"produzione\" FROM \"autogen\".\"data\" WHERE (\"device\" = 'SDM2301.1' AND \"type\" = 'Import') AND $timeFilter GROUP BY time(1d) fill(null) tz('Europe/Rome')\n)\nGROUP BY time(1d) fill(null) tz('Europe/Rome')",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 16, "x": 8, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "alias": "Risparmio del mese",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT (mean(\"produzione\") - mean(\"immissione\")) * [[price]] as \"autoconsumo\"  FROM\n( \nSELECT difference(last(\"value\")) as \"prelievo\" FROM \"autogen\".\"data\" WHERE (\"device\" = 'SDM2301.2' AND \"type\" = 'Import') AND $timeFilter GROUP BY time(1d) fill(null) tz('Europe/Rome')\n), \n(\nSELECT difference(last(\"value\")) as \"immissione\" FROM \"autogen\".\"data\" WHERE (\"device\" = 'SDM2301.2' AND \"type\" = 'Export') AND $timeFilter GROUP BY time(1d) fill(null) tz('Europe/Rome')\n),\n(\nSELECT difference(last(\"value\")) as \"produzione\" FROM \"autogen\".\"data\" WHERE (\"device\" = 'SDM2301.1' AND \"type\" = 'Import') AND $timeFilter GROUP BY time(1d) fill(null) tz('Europe/Rome')\n)\nGROUP BY time(1d) fill(null) tz('Europe/Rome')",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Spesa del mese",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT (difference(last(\"value\"))) * [[price]] FROM \"data\" WHERE (\"device\" = 'SDM2301.2' AND \"type\" = 'Import') AND $timeFilter GROUP BY time(24h) fill(previous) tz('Europe/Rome')",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Produzione e Consumo Giornaliera - Settimanale",
   "type": "corpglory-multibar-graph-panel",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 46 },
   "yaxes": [
    { "format": "kwatth", "label": "Energia (KWh)" }
   ],
   "targets": [
    {
     "alias": "Inverter",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT ((integral(\"Verbrauch\")  / 3600) + (integral(\"Einspeisung\") / 3600) - (integral(\"Bezug\") / 3600)) / 1000 FROM \"AC\" WHERE $timeFilter GROUP BY time(1d) fill(null) tz('Europe/Rome')",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Produzione SDM",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "data",
     "query": "SELECT difference(last(\"value\")) FROM \"data\" WHERE (\"device\" = 'SDM2301.1' AND \"type\" = 'Import') AND $timeFilter GROUP BY time(1d) fill(previous) tz('Europe/Rome')",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Immissione",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT difference(last(\"value\")) FROM \"data\" WHERE (\"device\" = 'SDM2301.2' AND \"type\" = 'Export') AND $timeFilter GROUP BY time(1d) fill(null) tz('Europe/Rome')",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "autoconsumo",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"produzione\") - mean(\"immissione\") as \"autoconsumo\"  FROM\n( \nSELECT difference(last(\"value\")) as \"prelievo\" FROM \"autogen\".\"data\" WHERE (\"device\" = 'SDM2301.2' AND \"type\" = 'Import') AND $timeFilter GROUP BY time(1d) fill(null) tz('Europe/Rome')\n), \n(\nSELECT difference(last(\"value\")) as \"immissione\" FROM \"autogen\".\"data\" WHERE (\"device\" = 'SDM2301.2' AND \"type\" = 'Export') AND $timeFilter GROUP BY time(1d) fill(null) tz('Europe/Rome')\n),\n(\nSELECT difference(last(\"value\")) as \"produzione\" FROM \"autogen\".\"data\" WHERE (\"device\" = 'SDM2301.1' AND \"type\" = 'Import') AND $timeFilter GROUP BY time(1d) fill(null) tz('Europe/Rome')\n)\nGROUP BY time(1d) fill(null) tz('Europe/Rome')",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Consumo",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"prelievo\") + mean(\"produzione\") - mean(\"immissione\") as \"consumo\"  FROM\n( \nSELECT difference(last(\"value\")) as \"prelievo\" FROM \"autogen\".\"data\" WHERE (\"device\" = 'SDM2301.2' AND \"type\" = 'Import') AND $timeFilter GROUP BY time(1d) fill(null) tz('Europe/Rome')\n), \n(\nSELECT difference(last(\"value\")) as \"immissione\" FROM \"autogen\".\"data\" WHERE (\"device\" = 'SDM2301.2' AND \"type\" = 'Export') AND $timeFilter GROUP BY time(1d) fill(null) tz('Europe/Rome')\n),\n(\nSELECT difference(last(\"value\")) as \"produzione\" FROM \"autogen\".\"data\" WHERE (\"device\" = 'SDM2301.1' AND \"type\" = 'Import') AND $timeFilter GROUP BY time(1d) fill(null) tz('Europe/Rome')\n)\nGROUP BY time(1d) fill(null) tz('Europe/Rome')",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Prelievo SDM",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT difference(last(\"value\")) FROM \"data\" WHERE (\"device\" = 'SDM2301.2' AND \"type\" = 'Import') AND $timeFilter GROUP BY time(1d) fill(null) tz('Europe/Rome')",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 8, "x": 0, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "alias": "Produzione di oggi",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT difference(last(\"value\")) FROM \"data\" WHERE (\"device\" = 'SDM2301.1' AND \"type\" = 'Import') AND $timeFilter GROUP BY time(24h) fill(previous) tz('Europe/Rome')",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 8, "x": 8, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "alias": "Prelievo di oggi",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT difference(last(\"value\")) FROM \"data\" WHERE (\"device\" = 'SDM2301.2' AND \"type\" = 'Import') AND $timeFilter GROUP BY time(24h) fill(previous) tz('Europe/Rome')",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 8, "x": 16, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "kwatt" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "alias": "Prelievo Totale",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT last(\"value\") FROM \"data\" WHERE (\"device\" = 'SDM2301.2' AND \"type\" = 'Import') AND $timeFilter GROUP BY time($__interval) fill(previous) tz('Europe/Rome')",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 8, "x": 0, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "kwatt" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "alias": "Autoconsumo",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"produzione\") - mean(\"immissione\") as \"autoconsumo\"  FROM\n( \nSELECT difference(last(\"value\")) as \"prelievo\" FROM \"autogen\".\"data\" WHERE (\"device\" = 'SDM2301.2' AND \"type\" = 'Import') AND $timeFilter GROUP BY time(1d) fill(null) tz('Europe/Rome')\n), \n(\nSELECT difference(last(\"value\")) as \"immissione\" FROM \"autogen\".\"data\" WHERE (\"device\" = 'SDM2301.2' AND \"type\" = 'Export') AND $timeFilter GROUP BY time(1d) fill(null) tz('Europe/Rome')\n),\n(\nSELECT difference(last(\"value\")) as \"produzione\" FROM \"autogen\".\"data\" WHERE (\"device\" = 'SDM2301.1' AND \"type\" = 'Import') AND $timeFilter GROUP BY time(1d) fill(null) tz('Europe/Rome')\n)\nGROUP BY time(1d) fill(null) tz('Europe/Rome')",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 8, "x": 8, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "alias": "Consumo di oggi",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"prelievo\") + mean(\"produzione\") - mean(\"immissione\") as \"consumo\"  FROM\n( \nSELECT difference(last(\"value\")) as \"prelievo\" FROM \"autogen\".\"data\" WHERE (\"device\" = 'SDM2301.2' AND \"type\" = 'Import') AND $timeFilter GROUP BY time(1d) fill(null) tz('Europe/Rome')\n), \n(\nSELECT difference(last(\"value\")) as \"immissione\" FROM \"autogen\".\"data\" WHERE (\"device\" = 'SDM2301.2' AND \"type\" = 'Export') AND $timeFilter GROUP BY time(1d) fill(null) tz('Europe/Rome')\n),\n(\nSELECT difference(last(\"value\")) as \"produzione\" FROM \"autogen\".\"data\" WHERE (\"device\" = 'SDM2301.1' AND \"type\" = 'Import') AND $timeFilter GROUP BY time(1d) fill(null) tz('Europe/Rome')\n)\nGROUP BY time(1d) fill(null) tz('Europe/Rome')",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 8, "x": 16, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "kwatt" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "alias": "Export Totale",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT last(\"value\") FROM \"data\" WHERE (\"device\" = 'SDM2301.2' AND \"type\" = 'Export') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 8, "x": 0, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "kg" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expression": "0.4 * $E", "type": "math" }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 8, "x": 8, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "alias": "Produzione Totale Inverter",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT (last(\"Wh_Gesamt\")) / 1000 FROM \"Summen\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 8, "x": 16, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "alias": "Produzione di oggi",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT last(\"value\") FROM \"data\" WHERE (\"device\" = 'SDM2301.1' AND \"type\" = 'Import') AND $timeFilter GROUP BY time($__interval) fill(previous) tz('Europe/Rome')",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}